### ISSUE TITLE
xbow-check on finished job and insufficient local machine storage

### ISSUE THREAD

**Issue by athina1** [ChrisSuess/Project-Xbow#22]
As xbow-check copies the generated data from a finished job to your local machine and then deletes it from the cloud, do the data remain on the cloud if the local machine has insufficient storage?

**Comment by ChrisSuess** [comment]
In the xbow-check code it transfers the data back to your local machine before removing it from the cloud. If the transfer stage fails then it doesn't continue to the next part of the code so the data remains in the cloud. When sufficient space is available the command xbow-check can be rerun and and the data will be pooled back to your local machine.

I have tested this to be true and it has worked like this for me. If you find it to behave otherwise for you please let me know!
