### ISSUE TITLE
error with xbow-create_cluster

### ISSUE THREAD

**Issue by athina1** [ChrisSuess/Project-Xbow#27]
[pazam3@frost .xbow]$ xbow-create_cluster
Scheduler already running, now starting workers. This may take some time...
Traceback (most recent call last):
  File "/users/pazam3/.local/bin/xbow-create_cluster", line 61, in <module>
    user_data = user_data + extra_data
NameError: name 'extra_data' is not defined

**Comment by OleinikovasV** [comment]
Hi!
This seems like a real bug to me that still exists in the master version of the code.
In case your server workers are not launched successfully from in the first instance, it seem that the scheduler can still be setup and running.
Then the second time you are trying to run the **xbow-create_cluster** line 102 in [xbow-create_cluster](https://github.com/ChrisSuess/Project-Xbow/blob/master/xbow/scripts) is True: `if len(schedulers) == 1:`, and so, `user_data`, `extra_data` and `final_data` never get defined before being used recursively later.
Thus, this should be fetched from the running scheduler, defined again, or the scheduler needs to be terminated when the workers are not successfully started.

At the moment the only work around is to terminate the scheduler manually and start again, otherwise - you always get this error.
